server:
  forward-headers-strategy: framework
hibernate:
  cache:
    use_second_level_cache: true
    region:
      factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
spring:
  profiles:
    active: dev
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  cache:
    names: getLocalizedCustomerStatuses,getLocalizedCustomerStates,getLocalizedRejectionReason,getLocalizedCustomerTypes,getLocalizedBooleanValues,getLocalizedProductAvailabilities,getSourceSystemNames,getLocalizedErrorCodes
  caffeine:
    spec: maximumSize=500,expireAfterAccess=3600s
jasypt:
  encryptor:
    bean: jasyptEncryptor
media:
  file:
    storage:
      base-path: /app/zmds-media-files
    api:
      products:
        base-path: /public/images/products
logging:
  level:
    root: info

version: @project.version@
